### ISSUE TITLE
About classification results

### ISSUE THREAD

**Issue by rstitation** [tudelft-iv/occluded_vehicle_acoustic_detection#2]
If the detected vehicle approaches the intersection from the left, when the detected vehicle passes the intersection and enters the non line of sight area on the right again, what is the classification result of the model? That is, will a vehicle moving away from the right be recognized as a vehicle approaching from the right?

**Comment by jkooij** [comment]
Hi, thanks for your question!

If you ask how we trained the model, then the answer is that for our dataset (Table I in the paper) we only extract training/validation/test samples when the vehicle is either still occluded behind the first (e.g. left corner) while approaching, or within line-of-sight. No samples are extracted when the vehicle disappeared again behind the other (e.g. right) corner. That means that we do not explicitly train the model to give a particular response after the vehicle has crossed the view, and this situation is also not explicitly evaluated in the initial ablation study (Table II).

However, we do see some occurrence of this effect in our online experiments where the trained model is applied in a sliding window. E.g. see Figure 8(a), where you can see that after the crossing, when the probability of "front" goes down, indeed the probability of "right" increases as one might expect. Vice versa the probability of "left" increases in Figure 8(b) after the vehicle moved right to left. So, while we did not explicitly train for this, in practice we can observe that our model will indeed recognize that the vehicle has moved behind the other corner when applied in an online filter. It appears that the reflection patterns that we classify appear sufficiently similar, even though the vehicle is moving away now.

Hope this answers your question.

**Comment by rstitation** [comment]
Thanks for your prompt answer. 

First of all, there have been some methods using millimeter wave radar and computer vision methods to detect non-line-of-sight vehicles. Your idea of using multi-channel acoustic information for non-line-of-sight vehicle detection is amazing. 

And your explanation is very detailed, you also gives the possible reason corresponding to the classification results. I agree with you very much. Due to the similarity of reflection patterns, the model classifies the vehicles that are moving away again. The question I asked was well answered by your answer.

Thank you for sharing your code on GitHub.

**Comment by hmyrst** [comment]
Hi, here I am again. I happened to see your article uploaded on arXiv. In the article there, Figure. 7 shows the prediction results for a longer time, that is, t0-te: [- 8s, 4s], rather than [- 6s, 3s] in the formal paper. Could you please tell me the duration of a complete piece of audio collected in your original data, and whether the measurement time after the car is blocked again is equal to the measurement time when the car first appears in the field of vision. Could you please send your original audio to me? and I will conduct research on the corresponding problems. Thank you very much for your work and hope your reply.

**Comment by hmyrst** [comment]
Hi, here I am again. I happened to see your article uploaded on arXiv. In the article there, Figure. 7 shows the prediction results for a longer time, that is, t0-te: [- 8s, 4s], rather than [- 6s, 3s] in the formal paper. Could you please tell me the duration of a complete piece of audio collected in your original data, and whether the measurement time after the car is blocked again is equal to the measurement time when the car first appears in the field of vision. Could you please send your original audio to me? and I will conduct research on the corresponding problems. Thank you very much for your work and hope your reply.
